### ISSUE TITLE
Learning a worked network example?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [alexpghayes/twittercache#8]
Hi @alexpghayes,

I am new to networks would you mind helping me through a first example with twitter cache? Following the tutorial, I was able to come up with something like:

```
graph <- get_network_as_tidygraph(core_only = F)
adjacency <- igraph::get.adjacency(graph)
graph <- igraph::graph_from_adjacency_matrix(adjacency)
plot(graph)
```
How would you name the nodes? How would you reduce the network to make it more readable? Sorry I wasn't familiar with the format of graph, so I wasn't able to figure this out on my own. Thank you!

**Comment by alexpghayes** [comment]
Hey @johnhenrypezzuto! Unfortunately I won't be able to write this up at the moment -- `twittercache` is about collecting network, but doesn't provide tools for analysis or visualization. I encourage you to look into the `igraph` package for details on how to analyze and plot networks!
